package network.palace.parkmanager.magicband;

public enum BandInventory {
    //    MAINMENU, PARKS, FOOD, MYPROFILE, SHOWSANDEVENTS, CUSTOMIZE, CUSTOMNAME, CUSTOMCOLOR, SPECIALCOLOR,
//    RIDESANDATTRACTIONS, RIDES, ATTRACTIONS, HOTELSANDRESORTS, HOTELS, MYHOTELROOMS, HOTELROOMS, HOTELCHECKOUT,
//    HOTELROOM, PLAYERSETTINGS, DESIGNSTATION, SHOPMAINMENU, FASTPASS, SHOPMENU, BACKPACK, LOCKER, SHOWTIMES,
//    WARDROBEMANAGER, STORAGE, PLAYERTIME, ACHIEVEMENTS;

    // Main Menu
    MAIN, FOOD, SHOWS, ATTRACTION_MENU, PARKS, SHOP, WARDROBE, HOTELS, PROFILE, VISIBILITY, CUSTOMIZE_BAND,
    // Attractions Menu
    ATTRACTION_LIST, WAIT_TIMES,
    // Parks Menu
    PARKS_WDW,
    // Customize MagicBand
    CUSTOMIZE_BAND_TYPE, CUSTOMIZE_BAND_NAME,
    // Show Timetable
    TIMETABLE
}
