package network.palace.parkmanager.magicband;

public enum BandInventory {
    //    MAINMENU, PARKS, FOOD, MYPROFILE, SHOWSANDEVENTS, CUSTOMIZE, CUSTOMNAME, CUSTOMCOLOR, SPECIALCOLOR,
//    RIDESANDATTRACTIONS, RIDES, ATTRACTIONS, HOTELSANDRESORTS, HOTELS, MYHOTELROOMS, HOTELROOMS, HOTELCHECKOUT,
//    HOTELROOM, PLAYERSETTINGS, DESIGNSTATION, SHOPMAINMENU, FASTPASS, SHOPMENU, BACKPACK, LOCKER, SHOWTIMES,
//    WARDROBEMANAGER, STORAGE, PLAYERTIME, ACHIEVEMENTS;

    // Main Menu
    MAIN, FOOD, SHOWS, ATTRACTION_MENU, ATTRACTION_LIST, WAIT_TIMES, PARKS, PARKS_WDW, SHOP, WARDROBE, HOTELS, PROFILE, VISIBILITY,
    // Show Timetable
    TIMETABLE
}
