package us.mcmagic.magicassistant.utils;

public enum InventoryType {
    MAINMENU, PARK, FOOD, PLAYERINFO, FRIENDLIST, SHOWSANDEVENTS, CUSTOMIZE, CUSTOMNAME, CUSTOMCOLOR, RIDESANDATTRACTIONS, RIDES, ATTRACTIONS, HOTELSANDRESORTS
}