package us.mcmagic.magicassistant.utils;

public enum InventoryType {
    MAINMENU, PARK, FOOD, MYPROFILE, FRIENDLIST, SHOWSANDEVENTS, CUSTOMIZE, CUSTOMNAME, CUSTOMCOLOR, SPECIALCOLOR, RIDESANDATTRACTIONS, RIDES, ATTRACTIONS, HOTELSANDRESORTS, HOTELS, MYHOTELROOMS, HOTELROOMS, HOTELCHECKOUT, HOTELROOM
}