package us.mcmagic.magicassistant.utils;

public enum InventoryType {
    MAINMENU, PARK, FOOD, MYPROFILE, SHOWSANDEVENTS, CUSTOMIZE, CUSTOMNAME, CUSTOMCOLOR, SPECIALCOLOR,
    RIDESANDATTRACTIONS, RIDES, ATTRACTIONS, HOTELSANDRESORTS, HOTELS, MYHOTELROOMS, HOTELROOMS, HOTELCHECKOUT,
    HOTELROOM, PLAYERSETTINGS, DESIGNSTATION
}