package us.mcmagic.magicassistant.handlers;

public enum InventoryType {
    MAINMENU, PARK, FOOD, MYPROFILE, SHOWSANDEVENTS, CUSTOMIZE, CUSTOMNAME, CUSTOMCOLOR, SPECIALCOLOR,
    RIDESANDATTRACTIONS, RIDES, ATTRACTIONS, HOTELSANDRESORTS, HOTELS, MYHOTELROOMS, HOTELROOMS, HOTELCHECKOUT,
    HOTELROOM, PLAYERSETTINGS, DESIGNSTATION, SHOPMAINMENU, FASTPASS, SHOPMENU, SHOWTIMES
}