package us.mcmagic.parkmanager.handlers;

public enum InventoryType {
    MAINMENU, PARK, FOOD, MYPROFILE, SHOWSANDEVENTS, CUSTOMIZE, CUSTOMNAME, CUSTOMCOLOR, SPECIALCOLOR,
    RIDESANDATTRACTIONS, RIDES, ATTRACTIONS, HOTELSANDRESORTS, HOTELS, MYHOTELROOMS, HOTELROOMS, HOTELCHECKOUT,
    HOTELROOM, PLAYERSETTINGS, DESIGNSTATION, SHOPMAINMENU, FASTPASS, SHOPMENU, BACKPACK, LOCKER, SHOWTIMES,
    WARDROBEMANAGER, STORAGE, PLAYERTIME, ACHIEVEMENTS
}